### ISSUE TITLE
Build Failed Regarding Swerve drive 

### ISSUE THREAD

**Issue by abhishekove** [gurbain/customization#1]
error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
         std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::Odometry>> odom_pub_;
              ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/include/swerve_controller/swerve_controller.h:122:14: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
         std::shared_ptr<realtime_tools::RealtimePublisher<tf::tfMessage>> tf_odom_pub_;
              ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp: In member function ‘void swerve_controller::SwerveController::updateOdometry(const ros::Time&)’:
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp:293:17: error: ‘odom_pub_’ was not declared in this scope
             if (odom_pub_->trylock())
                 ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp:306:36: error: ‘tf_odom_pub_’ was not declared in this scope
             if (enable_odom_tf_ && tf_odom_pub_->trylock())
                                    ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp: In member function ‘void swerve_controller::SwerveController::setOdomPubFields(ros::NodeHandle&, ros::NodeHandle&)’:
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp:483:9: error: ‘odom_pub_’ was not declared in this scope
         odom_pub_.reset(new realtime_tools::RealtimePublisher<nav_msgs::Odometry>(controller_nh,
         ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp:494:71: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
              0., 0., 0., 0., 0., static_cast<double>(pose_cov_list[5])};
                                                                       ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp:505:72: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
              0., 0., 0., 0., 0., static_cast<double>(twist_cov_list[5])};
                                                                        ^
/home/abhishek/Desktop/ROS-for-ROBOCON-2021/robocon_ws/src/ros_controllers-swerve-drive/swerve_controller/src/swerve_controller.cpp:507:9: error: ‘tf_odom_pub_’ was not declared in this scope
         tf_odom_pub_.reset(new realtime_tools::RealtimePublisher<tf::tfMessage>(root_nh,

**Comment by gurbain** [comment]
Hi,

I will close this issue because it's completely unrelated to this repo!! Maybe, that should go here: https://github.com/gurbain/ros_controllers/tree/swerve-drive ?

In any case, in your error message, it just seems that you need to add #include <memory>. I guess you just copy-pasted my branch and this include was brought in the cmake by a parent package from ros-controller. Your post is extremely unclear!

Gabriel
